### ISSUE TITLE
Make the `id` field's name and type changable.

### ISSUE THREAD

**Issue by magiclen** [thedodd/wither#39]
Sometimes we don't want that the **id** field is named `id`, and don't want it to be an `ObjectId` (`Option<mongodb::oid::ObjectId>` precisely).

Perhaps `wither` can allow the following code in the future:

```rust
#[derive(Serialize, Deserialize, Model)]
struct Document {
    #[model(id)]
    #[serde(rename = "_id")]
    uid: u64
}
```

**Comment by thedodd** [comment]
@magiclen I've given this a decent bit of thought since before setting out to create this crate even. I have some discussion points here: https://docs.rs/wither/0.8.0/wither/model/trait.Model.html#derive starting with the line `For now, it seems logical to disallow customization of the PK.`

What are your thoughts on that? Is there are case which can not be satisfied by simply adding a unique index to another field and using that as the PK? Is it mostly a matter of semantics and keeping things terse?

**Comment by thedodd** [comment]
@magiclen just wanted to see if you have any thoughts on the response above.
